name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1.3
        with:
          otp-version: 22.2
          elixir-version: 1.10.1

      - name: Install dependencies
        run: mix deps.get

      - name: Check mix format
        run: mix format --check-formatted

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pair:
          - erlang: 22.2
            elixir: 1.10.3
          - erlang: 22.1
            elixir: 1.9.4
          - erlang: 21.3
            elixir: 1.8.2
          - erlang: 20.3.1
            elixir: 1.7.4
          - erlang: 19.3
            elixir: 1.6.6
          - erlang: 18.3
            elixir: 1.5.3
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1.3
        with:
          otp-version: ${{matrix.pair.erlang}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Compile dependencies
        run: mix deps.compile

      - name: Compile application
        if: matrix.elixir != '1.10.3'
        run: mix compile
        env:
          MIX_ENV: test

      - name: Compile application treating warnings as errors (only for last Elixir version)
        if: matrix.elixir == '1.10.3'
        run: mix compile --warnings-as-errors
        env:
          MIX_ENV: test

      - name: Run tests
        run: mix test --include stdlib
