name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1.3
        with:
          otp-version: 23.0.2
          elixir-version: 1.10.3

      - name: Install dependencies
        run: mix deps.get

      - name: Check mix format
        run: mix format --check-formatted

  compile_without_warnings:
    name: Compile without warnings on the latest official Elixir version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1.3
        with:
          otp-version: 23.0.2
          elixir-version: 1.10.3

      - name: Install dependencies
        run: mix deps.get

      - name: Compile application treating warnings as errors
        run: mix compile --warnings-as-errors

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp-version: 18.3.4.11
            elixir: 1.5.3
          - otp-version: 19.3.6.13
            elixir: 1.6.6
          - otp-version: 19.3.6.13
            elixir: 1.7.4
          - otp-version: 20.3.8.26
            elixir: 1.8.2
          - otp-version: 20.3.8.26
            elixir: 1.9.4
          - otp-version: 21.3.8.16
            elixir: 1.10.3
          - otp-version: 23.0.2
            elixir: 1.10.3
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1.3
        with:
          otp-version: ${{matrix.otp-version}}
          elixir-version: ${{matrix.elixir}}

      - name: Install dependencies
        run: mix deps.get --only test

      - name: Run tests
        run: mix test --color --include stdlib
